namespace AutoInority.Command
{
    internal enum PriorityEnum
    {
        DEFAULT,

        MANAGE_CREATURE_1,

        MANAGE_CREATURE_2,

        MANAGE_CREATURE_3,

        MANAGE_CREATURE_4,

        MANAGE_CREATURE_5,

        FARM_CREATURE_1,

        FARM_CREATURE_2,

        FARM_CREATURE_3,

        FARM_CREATURE_4,

        FARM_CREATURE_5,

        SUPRESS_CREATURE_1,

        SUPRESS_ORDEAL_CREATURE_1,

        SUPRESS_CREATURE_2,

        SUPRESS_ORDEAL_CREATURE_2,

        SUPRESS_CREATURE_3,

        SUPRESS_ORDEAL_CREATURE_3,

        SUPRESS_CREATURE_4,

        SUPRESS_ORDEAL_CREATURE_4,

        SUPRESS_CREATURE_5,

        SUPRESS_ORDEAL_CREATURE_5,

        MANAGE_KIT,

        MANAGE_CREATURE_1_URGENT,

        MANAGE_CREATURE_2_URGENT,

        MANAGE_CREATURE_3_URGENT,

        RESCUE_PANIC_AGENT,

        MANAGE_CREATURE_4_URGENT,

        MANAGE_CREATURE_5_URGENT,
    }
}